env:
  matrix:
    - VERSION='5.6'
    - VERSION='5.7'
build:
  pre_ci:
    - sed -i -e s/VERSION/${VERSION}/g module.yaml
    - docker build --rm=true --pull=true --force-rm=true --no-cache=true --tag=mygento/mysql:$VERSION .
  pre_ci_boot:
    image_name: mygento/mysql
    image_tag: $VERSION
    pull: false
  ci:
     - mysql -V
  push:
    - docker push mygento/mysql:$VERSION

integrations:
    hub:
      - integrationName: Docker
        type: docker
        agent_only: true
